import { relations } from 'drizzle-orm';
import { boolean, integer, jsonb, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core';

// 1. Users table (Admins and registered users)
export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  uid: text('uid').notNull().unique(), // Firebase Auth UID or system generated
  email: text('email').notNull(),
  name: text('name').notNull(),
  role: text('role').notNull().default('student'), // 'admin' | 'student'
  createdAt: timestamp('created_at').defaultNow(),
});

// 2. Access Codes table (generated by Teacher for student activation)
export const accessCodes = pgTable('access_codes', {
  id: serial('id').primaryKey(),
  code: text('code').notNull().unique(),
  status: text('status').notNull().default('unused'), // 'unused' | 'used' | 'disabled'
  usedByStudentName: text('used_by_student_name'),
  usedByStudentPhone: text('used_by_student_phone'),
  usedAt: timestamp('used_at'),
  createdAt: timestamp('created_at').defaultNow(),
  note: text('note'), // e.g. "مجموعة الأحد - الصف الثالث الثانوي"
});

// 3. Students table (Students who activated via code)
export const students = pgTable('students', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  phone: text('phone').notNull(),
  codeUsed: text('code_used').notNull(),
  sessionToken: text('session_token').notNull().unique(),
  grade: text('grade').default('الصف الثالث الثانوي'),
  createdAt: timestamp('created_at').defaultNow(),
  lastActiveAt: timestamp('last_active_at').defaultNow(),
});

// 4. Lessons table (Video lessons with term/unit organization)
export const lessons = pgTable('lessons', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  description: text('description'),
  videoUrl: text('video_url').notNull(),
  durationMinutes: integer('duration_minutes').notNull().default(30),
  term: text('term').notNull().default('الترم الأول'), // الترم الأول / الترم الثاني
  unit: text('unit').notNull().default('Unit 1'),
  lessonNumber: integer('lesson_number').notNull().default(1),
  pdfAttachmentUrl: text('pdf_attachment_url'),
  isPublished: boolean('is_published').notNull().default(true),
  createdAt: timestamp('created_at').defaultNow(),
});

// 5. Exams table
export const exams = pgTable('exams', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  description: text('description'),
  timeLimitMinutes: integer('time_limit_minutes').notNull().default(20), // 0 means unlimited
  maxAttempts: integer('max_attempts').notNull().default(1),
  term: text('term').notNull().default('الترم الأول'),
  unit: text('unit').notNull().default('Unit 1'),
  passingScorePercent: integer('passing_score_percent').notNull().default(60),
  isPublished: boolean('is_published').notNull().default(true),
  createdAt: timestamp('created_at').defaultNow(),
});

// 6. Exam Questions table
export const examQuestions = pgTable('exam_questions', {
  id: serial('id').primaryKey(),
  examId: integer('exam_id').references(() => exams.id, { onDelete: 'cascade' }).notNull(),
  questionText: text('question_text').notNull(),
  type: text('type').notNull().default('multiple_choice'), // 'multiple_choice' | 'true_false'
  options: jsonb('options').$type<string[]>().notNull(), // ['Option A', 'Option B', ...]
  correctOptionIndex: integer('correct_option_index').notNull(), // 0-based
  explanation: text('explanation'),
  points: integer('points').notNull().default(1),
});

// 7. Exam Results table
export const examResults = pgTable('exam_results', {
  id: serial('id').primaryKey(),
  studentId: integer('student_id').references(() => students.id, { onDelete: 'cascade' }).notNull(),
  examId: integer('exam_id').references(() => exams.id, { onDelete: 'cascade' }).notNull(),
  studentName: text('student_name').notNull(),
  studentPhone: text('student_phone').notNull(),
  score: integer('score').notNull(),
  totalPossiblePoints: integer('total_possible_points').notNull(),
  scorePercent: integer('score_percent').notNull(),
  timeSpentSeconds: integer('time_spent_seconds').notNull(),
  answers: jsonb('answers').$type<Record<string, number>>().notNull(), // questionId -> chosenIndex
  attemptNumber: integer('attempt_number').notNull().default(1),
  passed: boolean('passed').notNull().default(false),
  createdAt: timestamp('created_at').defaultNow(),
});

// Relationships
export const examsRelations = relations(exams, ({ many }) => ({
  questions: many(examQuestions),
  results: many(examResults),
}));

export const examQuestionsRelations = relations(examQuestions, ({ one }) => ({
  exam: one(exams, {
    fields: [examQuestions.examId],
    references: [exams.id],
  }),
}));

export const examResultsRelations = relations(examResults, ({ one }) => ({
  exam: one(exams, {
    fields: [examResults.examId],
    references: [exams.id],
  }),
  student: one(students, {
    fields: [examResults.studentId],
    references: [students.id],
  }),
}));
